/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TransFill;

import static TransFill.TransFillMainWindow.rb;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Enumeration;
import java.util.Iterator;
import java.util.MissingResourceException;
import java.util.ResourceBundle;
import javax.swing.JFileChooser;
import javax.swing.JTree;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author mats
 */
public class TransFillMainWindow extends javax.swing.JFrame {

    private final FZ12Program fz12Program;
    
    
    /**
     * Creates new form C100ToolsMainWindow
     */
    public TransFillMainWindow() {
        initComponents();

        TransFillTransferHandler fz12TransferHandler = new TransFillTransferHandler();
        fz12Program = new FZ12Program("");
        fz12TransferHandler.setFZ12Program(fz12Program);
        fz12Program.setTextArea(jTAProgramArea);
        jTAProgramArea.setDragEnabled(true);
        jTAProgramArea.setTransferHandler( fz12TransferHandler );

        
    }

    final static ResourceBundle rb = ResourceBundle.getBundle("version"); 

    
    public static final String getRbTok(String propToken) { 
        String msg = ""; 
        try { 
            msg = rb.getString(propToken); 
        } catch (MissingResourceException e) { 
            System.err.println("Token ".concat(propToken).concat(" not in Propertyfile!")); 
        } 
        return msg; 
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAProgramArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAToolDataArea = new javax.swing.JTextArea();
        jBtnChangeTool = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArkiv = new javax.swing.JMenu();
        jMIReadArcFile = new javax.swing.JMenuItem();
        jMISaveArcFile = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMiSettings = new javax.swing.JMenuItem();
        jMenuTools = new javax.swing.JMenu();
        jMIBuildTreeFromMainProgram = new javax.swing.JMenuItem();
        jMIBuildTreeFromToolProgram = new javax.swing.JMenuItem();
        jMIBuildTreeFromMeasuredTools = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMIEnterToolTreeInArcFile = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMIBuildOdsToolList = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TransFill");

        jTAProgramArea.setColumns(20);
        jTAProgramArea.setRows(5);
        jTAProgramArea.setDragEnabled(true);
        jScrollPane1.setViewportView(jTAProgramArea);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Program");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Planlista");

        jTAToolDataArea.setColumns(20);
        jTAToolDataArea.setRows(5);
        jTAToolDataArea.setDragEnabled(true);
        jScrollPane3.setViewportView(jTAToolDataArea);

        jBtnChangeTool.setText("Bygg planlista");
        jBtnChangeTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChangeToolActionPerformed(evt);
            }
        });

        jMenuArkiv.setText("Arkiv");

        jMIReadArcFile.setText("Öppna FZ12-program");
        jMIReadArcFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIReadArcFileActionPerformed(evt);
            }
        });
        jMenuArkiv.add(jMIReadArcFile);

        jMISaveArcFile.setText("Spara FZ12-program");
        jMISaveArcFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISaveArcFileActionPerformed(evt);
            }
        });
        jMenuArkiv.add(jMISaveArcFile);
        jMenuArkiv.add(jSeparator4);

        jMiSettings.setText("Inställningar");
        jMiSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiSettingsActionPerformed(evt);
            }
        });
        jMenuArkiv.add(jMiSettings);

        jMenuBar1.add(jMenuArkiv);

        jMenuTools.setText("Verktyg");

        jMIBuildTreeFromMainProgram.setText("Bygg verktygsträd från programmet");
        jMIBuildTreeFromMainProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBuildTreeFromMainProgramActionPerformed(evt);
            }
        });
        jMenuTools.add(jMIBuildTreeFromMainProgram);

        jMIBuildTreeFromToolProgram.setText("Bygg verktygsträd från gamla verktygsdata");
        jMIBuildTreeFromToolProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBuildTreeFromToolProgramActionPerformed(evt);
            }
        });
        jMenuTools.add(jMIBuildTreeFromToolProgram);

        jMIBuildTreeFromMeasuredTools.setText("Bygg verktygsträd från inmätta verktyg");
        jMenuTools.add(jMIBuildTreeFromMeasuredTools);
        jMenuTools.add(jSeparator1);

        jMIEnterToolTreeInArcFile.setText("Sätt in verktygsträdet i arcfilen");
        jMIEnterToolTreeInArcFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEnterToolTreeInArcFileActionPerformed(evt);
            }
        });
        jMenuTools.add(jMIEnterToolTreeInArcFile);
        jMenuTools.add(jSeparator2);

        jMIBuildOdsToolList.setText("Skapa ods-verktygslista");
        jMIBuildOdsToolList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBuildOdsToolListActionPerformed(evt);
            }
        });
        jMenuTools.add(jMIBuildOdsToolList);

        jMenuBar1.add(jMenuTools);

        jMenu1.setText("Hjälp");

        jMenuItem2.setText("Om");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnChangeTool)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(14, 14, 14)
                .addComponent(jBtnChangeTool)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIReadArcFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIReadArcFileActionPerformed
        readFZ12Program();
    }//GEN-LAST:event_jMIReadArcFileActionPerformed

    private void jMIBuildTreeFromMainProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBuildTreeFromMainProgramActionPerformed
        analyseFZ12Program();
    }//GEN-LAST:event_jMIBuildTreeFromMainProgramActionPerformed

    private void jMIBuildTreeFromToolProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBuildTreeFromToolProgramActionPerformed
    }//GEN-LAST:event_jMIBuildTreeFromToolProgramActionPerformed

    private void jBtnChangeToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnChangeToolActionPerformed
        fz12Program.analyseMainProgram();
    }//GEN-LAST:event_jBtnChangeToolActionPerformed

    private void jMISaveArcFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISaveArcFileActionPerformed
        saveArcFile();
    }//GEN-LAST:event_jMISaveArcFileActionPerformed

    private void jMIEnterToolTreeInArcFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEnterToolTreeInArcFileActionPerformed
        //enterToolTreeInArcFile();
    }//GEN-LAST:event_jMIEnterToolTreeInArcFileActionPerformed

    private void jMIBuildOdsToolListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBuildOdsToolListActionPerformed
    }//GEN-LAST:event_jMIBuildOdsToolListActionPerformed

    private void jMiSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiSettingsActionPerformed
        showSettingsDialog();
    }//GEN-LAST:event_jMiSettingsActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AboutDialog aboutDialog = new AboutDialog(this, true);
        aboutDialog.setBuildNr( getRbTok("BUILD") );
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransFillMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransFillMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransFillMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransFillMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TransFillMainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnChangeTool;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMIBuildOdsToolList;
    private javax.swing.JMenuItem jMIBuildTreeFromMainProgram;
    private javax.swing.JMenuItem jMIBuildTreeFromMeasuredTools;
    private javax.swing.JMenuItem jMIBuildTreeFromToolProgram;
    private javax.swing.JMenuItem jMIEnterToolTreeInArcFile;
    private javax.swing.JMenuItem jMIReadArcFile;
    private javax.swing.JMenuItem jMISaveArcFile;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuArkiv;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JMenuItem jMiSettings;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTextArea jTAProgramArea;
    private javax.swing.JTextArea jTAToolDataArea;
    // End of variables declaration//GEN-END:variables

    private void readFZ12Program() {

        String fileName = getWantedFile();
        if ( fileName != null ) {
            fz12Program.readFile(fileName);
        }
    }

    private String getWantedFile() {
        JFileChooser jfc = new JFileChooser();
        int result = jfc.showOpenDialog(null);
        if ( result == JFileChooser.APPROVE_OPTION ) {
            return jfc.getSelectedFile().getAbsolutePath();
        } else {
            return null;
        }
           
    }

    private void analyseFZ12Program() {
        if ( fz12Program != null ) {
            fz12Program.analyseMainProgram();
        }
    }

    private void saveArcFile() {
        fz12Program.saveFile();
    }


    private void showSettingsDialog() {
        TransFillPreferences c100Preferences = TransFillPreferences.getInstance();
        c100Preferences.showPrefDialog();
    }



}
